// Destination + course directory data for the W5 prototype.
//
// Myrtle Beach is the one "live" destination, seeded with the 15 pilot-batch
// course records already researched in the "Myrtle Beach Golf Courses"
// Notion database (W4 pilot). Every other destination is a stub so the
// Explore grid reads like the real 30-destination target list (per the W3
// research task) without fabricating course data that hasn't been
// researched yet.
//
// Lodging and dining are intentionally NOT included yet -- no real data has
// been researched for either (W4/W5/W6 destination-profile tasks are still
// "Not started" in Notion). The Destination Detail screen shows those two
// tabs as explicit "Coming soon" placeholders rather than inventing venues.

export const DESTINATIONS = [
  {
    slug: "myrtle-beach-sc",
    name: "Myrtle Beach, SC",
    state: "South Carolina",
    tagline: "The Grand Strand — 90+ courses along the Carolina coast",
    heroDescription:
      "The highest concentration of golf courses in the US, spanning Myrtle Beach, North Myrtle Beach, Pawleys Island, Murrells Inlet, and the Calabash/Sunset Beach NC border towns. Courses range from Golden Age classics to modern signature designs, most within a 30-minute drive of the beach.",
    status: "live",
    courseCount: 15,
  },
  {
    slug: "hilton-head-sc",
    name: "Hilton Head Island, SC",
    state: "South Carolina",
    tagline: "Lowcountry resort golf, Harbour Town and beyond",
    heroDescription: "Destination profile research not started yet (W4/W5).",
    status: "coming_soon",
    courseCount: 0,
  },
  {
    slug: "pinehurst-nc",
    name: "Pinehurst, NC",
    state: "North Carolina",
    tagline: "The Cradle of American Golf",
    heroDescription: "Destination profile research not started yet (W4/W5).",
    status: "coming_soon",
    courseCount: 0,
  },
  {
    slug: "scottsdale-az",
    name: "Scottsdale, AZ",
    state: "Arizona",
    tagline: "Desert target golf and resort clusters",
    heroDescription: "Destination profile research not started yet (W6).",
    status: "coming_soon",
    courseCount: 0,
  },
  {
    slug: "orlando-fl",
    name: "Orlando, FL",
    state: "Florida",
    tagline: "Champions Gate, Reunion, and central Florida resort golf",
    heroDescription: "Destination profile research not started yet (W6).",
    status: "coming_soon",
    courseCount: 0,
  },
  {
    slug: "phoenix-mesa-az",
    name: "Phoenix / Mesa, AZ",
    state: "Arizona",
    tagline: "Spring-training season golf hub",
    heroDescription: "Destination profile research not started yet (W6).",
    status: "coming_soon",
    courseCount: 0,
  },
];

// The 15 pilot-batch rows pulled from the "Myrtle Beach Golf Courses" Notion
// database (Pilot Batch = true, Status = In progress as of 2026-08-28).
// Fields left blank in Notion (yardage, slope/rating, dress code, greens
// fee) stay blank here rather than being invented.
export const MYRTLE_BEACH_COURSES = [
  {
    slug: "caledonia-golf-fish-club",
    name: "Caledonia Golf & Fish Club",
    area: "Pawleys Island",
    courseType: "Public",
    designer: "Mike Strantz",
    holes: 18,
    par: "70",
    yardage: "6,526 yards (overall)",
    slopeRating: "",
    dressCode: "",
    greensFeeRange: "",
    amenities: ["Pro Shop", "Restaurant", "Bar", "Lessons"],
    description:
      "One of the Hammock Coast's most acclaimed layouts, ranked in Top 100 lists since 1994. 18 signature holes routed through oaks and streams with an iconic marsh-bordered finishing hole.",
    address: "369 Caledonia Dr, Pawleys Island, SC 29585",
    phone: "1-800-483-6800",
    website: "https://www.caledoniagolfandfishclub.com",
    bookingLink: "https://caledoniagolfandfishclub.com/tee-times",
    photoUrl:
      "https://caledoniagolfandfishclub.com/wp-content/uploads/2019/03/caledonia-golf-vacations-banner-768x402.jpg",
  },
  {
    slug: "true-blue-golf-club",
    name: "True Blue Golf Club",
    area: "Pawleys Island",
    courseType: "Public",
    designer: "Mike Strantz",
    holes: null,
    par: "",
    yardage: "",
    slopeRating: "",
    dressCode: "",
    greensFeeRange: "",
    amenities: ["Driving Range", "Pro Shop", "Restaurant", "Practice Green"],
    description:
      "Mike Strantz design with dramatic terrain and undulating greens on the Waccamaw Golf Trail; consistently ranked among South Carolina's top public courses. 18-acre practice facility.",
    address: "900 Blue Stem Drive, Pawleys Island, SC 29585",
    phone: "1-888-483-6800",
    website: "https://www.truebluegolf.com",
    bookingLink: "https://search.guestdesk.com/reservations/TrueBlueCaledonia/golf/7587",
    photoUrl:
      "https://www.truebluegolf.com/wp-content/uploads/2019/04/caledonia-golf-vacations-banner-768x402.jpg",
  },
  {
    slug: "barefoot-resort-fazio",
    name: "Barefoot Resort & Golf (Fazio Course)",
    area: "North Myrtle Beach",
    courseType: "Resort",
    designer: "Tom Fazio",
    holes: null,
    par: "",
    yardage: "",
    slopeRating: "",
    dressCode: "",
    greensFeeRange: "Sold as packages; no fixed public rate listed",
    amenities: ["Driving Range", "Pro Shop"],
    description:
      "Tom Fazio championship design at Barefoot Resort with strategic bunkering, wide fairways, and marsh views. One of four named courses at the resort (Fazio, Dye, Love, Norman).",
    address: "4980 Barefoot Resort Bridge Rd., North Myrtle Beach, SC 29582",
    phone: "843-390-3200",
    website: "https://www.barefootgolf.com",
    bookingLink: "https://barefootresort.omnitech.golf/teetimes/searchmatrix",
    photoUrl: "https://barefootgolf.com/wp-content/uploads/2018/01/fazio-featured2.jpg",
  },
  {
    slug: "world-tour-golf-links",
    name: "World Tour Golf Links",
    area: "Myrtle Beach",
    courseType: "Public",
    designer: "Mel Graham",
    holes: 18,
    par: "",
    yardage: "",
    slopeRating: "",
    dressCode: "",
    greensFeeRange: "",
    amenities: ["Driving Range", "Pro Shop", "Restaurant", "Lessons", "Bar"],
    description:
      "Novelty 18-hole course where each hole is inspired by an iconic course worldwide (Augusta National, St. Andrews, and others); now also home to \"The Bridge\" Toptracer range.",
    address: "2000 World Tour Blvd, Myrtle Beach, SC 29579",
    phone: "843-236-2000",
    website: "https://www.theworldtourgolf.com",
    bookingLink: "https://worldtour.teetimecentralonline.com/",
    photoUrl: "https://admin.theworldtourgolf.com/wp-content/uploads/2024/09/WorldTour-Background.png",
  },
  {
    slug: "wachesaw-plantation-east",
    name: "Wachesaw Plantation East",
    area: "Murrells Inlet",
    courseType: "",
    designer: "Clyde Johnston",
    holes: null,
    par: "",
    yardage: "4,995-6,933 yards across 5 tee sets",
    slopeRating: "",
    dressCode: "",
    greensFeeRange: "",
    amenities: ["Restaurant"],
    description:
      "Former rice plantation site in Murrells Inlet that has hosted LPGA events. Traditional Scottish-style design with five tee options and memorable finishing holes.",
    address: "",
    phone: "888-922-0027",
    website: "https://www.wachesaweast.com",
    bookingLink: "http://wachesaweast.quick18.com",
    photoUrl: "",
  },
  {
    slug: "tpc-myrtle-beach",
    name: "TPC Myrtle Beach",
    area: "Murrells Inlet",
    courseType: "Public",
    designer: "Tom Fazio",
    holes: 18,
    par: "72",
    yardage: "",
    slopeRating: "",
    dressCode: "",
    greensFeeRange: "",
    amenities: ["Driving Range", "Practice Green", "Pro Shop", "Restaurant", "Lessons"],
    description:
      "Championship 18-hole Tom Fazio design open to the public, known for tour-caliber difficulty and one of the best practice facilities on the Grand Strand. Has hosted numerous golf legends.",
    address: "1199 TPC Blvd, Murrells Inlet, SC 29576",
    phone: "843-357-3399",
    website: "https://www.tpcmyrtlebeach.com",
    bookingLink: "https://tpconline.teetimecentralonline.com/",
    photoUrl:
      "https://www.tpcmyrtlebeach.com/_next/image/?url=https%3A%2F%2Fadmin.tpcmyrtlebeach.com%2Fwp-content%2Fuploads%2F2023%2F11%2FTPC-Bkg1.png&w=3840&q=75",
  },
  {
    slug: "grande-dunes-resort-club",
    name: "Grande Dunes Resort Club",
    area: "Myrtle Beach",
    courseType: "Resort",
    designer: "Roger Rulewich",
    holes: null,
    par: "",
    yardage: "",
    slopeRating: "",
    dressCode: "",
    greensFeeRange: "",
    amenities: ["Pro Shop", "Restaurant", "Practice Green", "Bar", "Driving Range", "Lessons"],
    description:
      "Roger Rulewich design voted Myrtle Beach's best course and ranked among America's 100 Greatest Public Courses. Five holes run along the Intracoastal Waterway; recently renovated clubhouse.",
    address: "8700 Golf Village Lane, Myrtle Beach, SC 29579",
    phone: "843-315-0333",
    website: "https://www.grandedunesgolf.com",
    bookingLink: "https://grandedunesonline.teetimecentralonline.com/",
    photoUrl: "https://www.grandedunesgolf.com/wp-content/uploads/2026/04/Grande-Dunes-Clubhouse-scaled.jpg",
  },
  {
    slug: "tidewater-golf-club",
    name: "Tidewater Golf Club",
    area: "North Myrtle Beach",
    courseType: "Public",
    designer: "",
    holes: null,
    par: "",
    yardage: "",
    slopeRating: "",
    dressCode: "",
    greensFeeRange: "",
    amenities: ["Driving Range", "Pro Shop", "Restaurant", "Lessons", "Bar"],
    description:
      "Championship public course between the Intracoastal Waterway and Cherry Grove Inlet, ranked among the nation's top 100 public courses.",
    address: "1400 Tidewater Drive, North Myrtle Beach, SC 29582",
    phone: "(843) 913-2424",
    website: "https://www.tidewatergolf.com",
    bookingLink: "https://tidewater.omnitech.golf/teetimes/searchmatrix",
    photoUrl: "",
  },
  {
    slug: "pearl-golf-links",
    name: "The Pearl Golf Links",
    area: "Calabash NC",
    courseType: "Public",
    designer: "Dan Maples",
    holes: 27,
    par: "",
    yardage: "",
    slopeRating: "",
    dressCode: "",
    greensFeeRange: "",
    amenities: ["Pro Shop", "Bar"],
    description:
      "27-hole public facility (three nine-hole courses) designed by Dan Maples in 1987, set among marsh and woodland scenery along the Calabash River.",
    address: "1300 Pearl Blvd., Calabash, NC 28467",
    phone: "910.579.8132",
    website: "https://www.thepearlgolf.com",
    bookingLink: "https://pearl-golf-links.book.teeitup.com/",
    photoUrl: "https://thepearlgolf.com/wp-content/uploads/2023/11/DSC_5457-copyaa-scaled.jpg",
  },
  {
    slug: "man-o-war-golf-club",
    name: "Man O'War Golf Club",
    area: "Myrtle Beach",
    courseType: "Public",
    designer: "Dan Maples",
    holes: 18,
    par: "72",
    yardage: "6,967 yards from the black tees",
    slopeRating: "",
    dressCode: "",
    greensFeeRange: "",
    amenities: [],
    description:
      "Par-72 Dan Maples design built around an 80-acre lake, with water in play on nearly every hole and narrow, risk-reward fairways.",
    address: "5601 Leeshire Blvd., Myrtle Beach, SC 29579",
    phone: "",
    website: "https://www.manowargolfcourse.com",
    bookingLink: "",
    photoUrl: "",
  },
  {
    slug: "pine-lakes-country-club",
    name: "Pine Lakes Country Club",
    area: "Myrtle Beach",
    courseType: "Private",
    designer: "Robert White",
    holes: 18,
    par: "70",
    yardage: "",
    slopeRating: "",
    dressCode: "",
    greensFeeRange: "",
    amenities: ["Pro Shop", "Restaurant", "Bar", "Lessons"],
    description:
      "Myrtle Beach's first golf course, opened in 1927. Golden Age design by Robert White, first president of the PGA of America; less than half a mile from the ocean.",
    address: "5603 Granddaddy Drive, Myrtle Beach, SC 29577",
    phone: "(843) 315-7700",
    website: "https://www.pinelakes.com",
    bookingLink: "https://pinelakes.teetimecentralonline.com",
    photoUrl: "https://pinelakes.com/wp-content/uploads/2026/03/Pine-Lakes-9-Green-High-021026-DS-1.jpg",
  },
  {
    slug: "myrtle-beach-national-kings-north",
    name: "Myrtle Beach National (King's North)",
    area: "Myrtle Beach",
    courseType: "Public",
    designer: "Arnold Palmer",
    holes: null,
    par: "",
    yardage: "",
    slopeRating: "",
    dressCode: "",
    greensFeeRange: "",
    amenities: ["Pro Shop", "Restaurant", "Club Rentals"],
    description:
      "Iconic Arnold Palmer design, fully renovated in 2025, ranked among America's 100 Greatest Public Courses. Features \"The Gambler,\" a par 5 with an alternate island fairway.",
    address: "4900 National Drive, Myrtle Beach, SC 29579",
    phone: "(843) 448-2300",
    website: "https://www.myrtlebeachnational.com",
    bookingLink: "https://mbnkings.teetimecentralonline.com/",
    photoUrl: "https://www.myrtlebeachnational.com/wp-content/uploads/2025/05/Untitled-design-44.png",
  },
  {
    slug: "dunes-golf-beach-club",
    name: "The Dunes Golf & Beach Club",
    area: "Myrtle Beach",
    courseType: "Private",
    designer: "Robert Trent Jones",
    holes: null,
    par: "",
    yardage: "",
    slopeRating: "",
    dressCode: "",
    greensFeeRange: "",
    amenities: [],
    description:
      "Historic Robert Trent Jones championship course, \"A Beach Oasis Since 1948,\" and home of the PGA Tour's Myrtle Beach Classic.",
    address: "9000 N. Ocean Boulevard, Myrtle Beach, SC 29572",
    phone: "(843) 449-5236",
    website: "https://www.thedunesclub.com",
    bookingLink: "",
    photoUrl: "https://www.thedunesclub.com/images/dynamic/getImage.gif?ID=118159",
  },
  {
    slug: "legends-golf-resort-moorland",
    name: "Legends Golf Resort (Moorland Course)",
    area: "Myrtle Beach",
    courseType: "Resort",
    designer: "P.B. Dye",
    holes: null,
    par: "",
    yardage: "",
    slopeRating: "",
    dressCode: "",
    greensFeeRange: "",
    amenities: ["Driving Range", "Restaurant", "Bar"],
    description:
      "P.B. Dye design with dramatic elevation changes and bold green complexes, one of three courses (with Heathland and Parkland) at The Legends complex, plus on-site lodging.",
    address: "1500 Legends Dr., Myrtle Beach, SC 29579",
    phone: "843-236-9318",
    website: "https://www.legendsgolf.com",
    bookingLink:
      "https://letsgo.golf/the-legends-golf-complex-heathland-course/teeTimes/the-legends-golf-resort-heathland-south-carolina",
    photoUrl: "https://www.legendsgolf.com/Images/Library/LEMO2.jpeg",
  },
];

export function getDestinationBySlug(slug) {
  return DESTINATIONS.find((d) => d.slug === slug) || null;
}

export function getCoursesForDestination(slug) {
  if (slug === "myrtle-beach-sc") return MYRTLE_BEACH_COURSES;
  return [];
}

export function getCourseBySlug(destinationSlug, courseSlug) {
  return getCoursesForDestination(destinationSlug).find((c) => c.slug === courseSlug) || null;
}
